name: Check
on: push
jobs:
  checkCodeStyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
  build:
#    needs: [checkCodeStyle]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Maven Package
        run: mvn clean compile package
      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar